sudo: required

language: node_js
node_js:
  - "10.9.0"

cache:
  directories:
  - node_modules
  - frontend/node_modules
  - cp/node_modules

services:
  - docker

before_install:
  - docker build -t websuite .