version: "3"
services:
  websuite_core:
    build: images/websuite-core
    image: websuite-core
    network_mode: "host"
    restart: always
    depends_on:
      - websuite_synchronize
    volumes:
      - ./vol/data:/opt/websuite/data
      - ./vol/logs:/opt/websuite/logs
  websuite_synchronize:
    build: images/websuite-synchronize
    image: websuite-synchronize
    restart: always